theme: jekyll-theme-slate
# SEO settings
title: "Milena's"
title2: "Set of elements " 
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url:  https://milenalavanchy.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/MilenaLavanchy/milenalavanchy.github.io/
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Milena Lavanchy"
  job      : "Explorer"
  bio      : "My place is where my heart belongs to and I'm excited to explore its lands and waters :)"
  thumb    : /images/author.jpg
  email    : milena.lavanchy@gmail.com
  url      : http://heiswayi.github.io
  github   : http://github.com/milenalavanchy
#twitter  : http://twitter.com/
#linkedin : http://linkedin.com/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - jekyll-paginate
  - jekyll-feed

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
